import 'package:hive_flutter/hive_flutter.dart';
import '../../core/constants/app_constants.dart';

// ── HiveObject model imports ──────────────────────────────────────────────────
// Un-comment each line as the corresponding model file is generated by
// build_runner. Adapter registration in main.dart follows the same pattern.
import 'models/expense_entry.dart';
import 'models/pending_sms_entry.dart';
import 'models/debt_entry.dart';

/// Singleton service that owns Hive initialisation and all box accessors.
///
/// Usage:
///   await HiveService.instance.init();          // call once in main.dart
///   final box = HiveService.instance.expenses;  // then use anywhere
///
/// All Hive reads/writes in the app must go through this service — never
/// open boxes directly from widgets or providers.
class HiveService {
  HiveService._();

  static final HiveService instance = HiveService._();

  // ── Opened box references ─────────────────────────────────────────────────

  late Box<dynamic> _expensesBox;
  late Box<dynamic> _userProfileBox;
  late Box<dynamic> _simulationsBox;
  late Box<dynamic> _cibilBox;
  late Box<dynamic> _debtsBox;

  // ── Public accessors ──────────────────────────────────────────────────────

  /// Box storing [ExpenseEntry] objects for the Expense Tracker module.
  Box<dynamic> get expenses => _expensesBox;

  /// Box storing the user's profile and app-level preferences.
  Box<dynamic> get userProfile => _userProfileBox;

  /// Box caching the last SIP / Lumpsum / Hybrid simulation result.
  Box<dynamic> get simulations => _simulationsBox;

  /// Box storing the last CIBIL calculator inputs and computed result.
  Box<dynamic> get cibil => _cibilBox;

  /// Box storing friend debt entries for the Debt Tracker module.
  Box<dynamic> get debts => _debtsBox;

  // ── Initialisation ────────────────────────────────────────────────────────

  /// Initialises Hive and opens all application boxes.
  ///
  /// Must be awaited before [runApp] is called.
  /// Register all Hive type adapters here before opening boxes.
  Future<void> init() async {
    // Initialise Flutter-specific path resolution (documents directory etc.)
    await Hive.initFlutter();

    // ── Register type adapters ──────────────────────────────────────────────
    if (!Hive.isAdapterRegistered(1)) {
      Hive.registerAdapter(ExpenseEntryAdapter());
    }
    if (!Hive.isAdapterRegistered(2)) {
      Hive.registerAdapter(PendingSmsEntryAdapter());
    }
    if (!Hive.isAdapterRegistered(5)) {
      Hive.registerAdapter(DebtEntryAdapter());
    }

    // ── Open boxes ─────────────────────────────────────────────────────────
    _expensesBox    = await Hive.openBox<dynamic>(AppConstants.hiveBoxExpenses);
    _userProfileBox = await Hive.openBox<dynamic>(AppConstants.hiveBoxUser);
    _simulationsBox = await Hive.openBox<dynamic>(AppConstants.hiveBoxSimulations);
    _cibilBox       = await Hive.openBox<dynamic>(AppConstants.hiveBoxCibil);
    _debtsBox       = await Hive.openBox<dynamic>(AppConstants.hiveBoxDebts);
  }

  // ── Convenience helpers ───────────────────────────────────────────────────

  /// Clears all boxes — used for logout / account wipe.
  Future<void> clearAll() async {
    await _expensesBox.clear();
    await _userProfileBox.clear();
    await _simulationsBox.clear();
    await _cibilBox.clear();
    await _debtsBox.clear();
  }

  /// Closes all open boxes. Call during app teardown (rarely needed).
  Future<void> closeAll() async {
    await Hive.close();
  }
}
